config/routes.rb
Rails.application.routes.draw do
  root 'users#occasions'

  devise_for :users

  resources :users do
    member do
      get :occasions
      get :events
    end
  end

  resources :events do
    member do
      get :guests
    end
  end

  get 'search', to: 'events#results'

  resources :attendances, only: [:create, :destroy]

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :guest, class_name: "User"
  belongs_to :occasion, class_name: "Event", :touch => true
  validates :guest_id, presence: true
  validates :occasion_id, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user, :touch => true
  validate :end_gt_start
  validates :user_id, presence: true
  validates :name, :location, :description, :host, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  has_many :passive_attendances, class_name: "Attendance",
                                 foreign_key: "occasion_id",
                                 dependent: :destroy
  has_many :guests, through: :passive_attendances, source: :guest

  def end_gt_start
    if timestart > timeend
      errors.add(:timeend, "can't be before the event starts")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_many :active_attendances, class_name: "Attendance",
                                foreign_key: "guest_id",
                                dependent: :destroy
  has_many :occasions, through: :active_attendances, source: :occasion

  def attend(event)
    active_attendances.create(occasion_id: event.id)
  end

  def unattend(event)
    active_attendances.find_by(occasion_id: event.id).destroy
  end

  def attending?(event)
    occasions.include?(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #include ActionController::Caching

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    event = Event.find(params[:occasion_id])
    current_user.attend(event)
    redirect_to event
  end

  def destroy
    event = Attendance.find(params[:id]).occasion
    current_user.unattend(event)
    redirect_to event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :destroy]
  respond_to :html
  cache_sweeper :event_sweeper

  caches_action :show
  caches_action :index

  def index
    @events = Event.all
    respond_with(@events)
  end

  def results
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def correct_user
      @event = current_user.events.find_by(id: params[:id])
      if @event.nil?
        flash[:alert] = "You are not logged in as the correct user."
        redirect_to root_url
      end
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :location, :timestart, :timeend, :description, :host)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend.html.erb
<%= form_for(current_user.active_attendances.build) do |f| %>
  <div><%= hidden_field_tag :occasion_id, @event.id %></div>
  <%= f.submit "Attend", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/events/_attend_form.html.erb
<% unless current_user == @user %>
  <div id="attend_form">
  <% if current_user.attending?(@event) %>
    <%= render 'unattend' %>
  <% else %>
    <%= render 'attend' %>
  <% end %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label "From" %><br>
    <%= f.datetime_select :timestart %>
  </div>
  <div class="field">
    <%= f.label "To" %><br>
    <%= f.datetime_select :timeend %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/events/_search_form.html.erb
<%= form_tag(search_path, :method => "get", class: "navbar-form", id: "search-form") do |f| %>
  <div class="search_form">
    <%= text_field_tag :keyword, params[:keyword], class: "search_form", placeholder: "Search events" %>
    <button type="submit" class="btn btn-primary-outline btn-sm">Search</button>
  </div>
<% end %>

app/views/events/_unattend.html.erb
<%= form_for(current_user.active_attendances.find_by(occasion_id: @event.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unattend", class: "btn btn-danger btn-sm" %>
<% end %>

app/views/events/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', event_path(@event) %> |
<%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>

app/views/events/index.html.erb
<h1>What's happening?</h1>

<div class="row">

    <% @events.each do |event| %>
    <% cache do %>
      <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4><%= event.name %> <small>Hosted by <%= event.host %></small></h4>
          </div>
          <div class="panel-body">
            <p>
              <span class="glyphicon glyphicon-map-marker"></span>
              <%= event.location %>
            </p>
            <p>
              <span class="glyphicon glyphicon-time"></span>
              <%= event.timestart.strftime("%B %-d, %l:%M %p") %>
            </p>
            <p><%= link_to 'View', event, class: "btn btn-primary btn-sm" %> <%= link_to 'Edit', edit_event_path(event), class: "btn btn-default btn-sm" %></p>
          </div>
        </div>
      </div>
  
   <% end %>
    <% end %>
</div>
<%= link_to 'New Event', new_event_path, class: "btn btn-primary btn-sm" %>

app/views/events/new.html.erb
<h1>Create an event:</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/results.html.erb
<% search_term = params[:keyword].to_s %>
<% render 'search_form' %>
<h1>Searching for "<%= search_term %>"</h1>

<div class="row">
    <!--<% @events.each do |event| %>-->
    <% cache ['event_list', event] do %>
      <% if search_term.in? event.name %>
        <div class="col-sm-4 col-md-4 col-lg-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4><%= event.name %> <small>Hosted by <%= event.host %></small></h4>
            </div>
            <div class="panel-body">
              <p>
                <span class="glyphicon glyphicon-map-marker"></span>
                <%= event.location %>
              </p>
              <p>
                <span class="glyphicon glyphicon-time"></span>
                <%= event.timestart.strftime("%B %-d, %l:%M %p") %>
              </p>
              <p><%= link_to 'View', event, class: "btn btn-primary btn-sm" %> <%= link_to 'Edit', edit_event_path(event), class: "btn btn-default btn-sm" %></p>
            </div>
          </div>
        </div>
      <!--<% end %>-->
      <% end %>
    <% end %>
</div>

app/views/events/show.html.erb
<div class="page-header">
  <h1><%= @event.name %> <small>Hosted by <%= @event.host %></small></h1>
</div>

<div class="well">
  <p>
    <span class="glyphicon glyphicon-map-marker"></span>
    <%= @event.location %>
  </p>

  <p>
    <span class="glyphicon glyphicon-time"></span>
    <% if @event.timestart.strftime("%A, %B %-d, %Y") == @event.timeend.strftime("%A, %B %-d, %Y") %>
      <%= @event.timestart.strftime("%A, %B %-d, %Y, %l:%M %p") %> to <%= @event.timeend.strftime("%l:%M %p") %>
    <% else %>
      <%= @event.timestart.strftime("%A, %B %-d, %Y, %l:%M %p") %> to <%= @event.timeend.strftime("%A, %B %-d, %Y, %l:%M %p") %>
    <% end %>
  </p>

  <p>
    <span class="glyphicon glyphicon-ok"></span>
    <%= @event.guests.count %>
    <% if @event.guests.count == 1 %>
      guest
    <% else %>
      guests
    <% end %>
  </p>
</div>
<%= render 'attend_form' %>
<br>
<div class="well">
  <p>
    <%= @event.description %>
  </p>
</div>

<%= link_to 'Back', events_path %>
<% if current_user.id == @event.user_id %> |
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happening</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
  integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ=="
  crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"
  integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ=="
  crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Happening</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="active"><a href="/events">Find Events</a></li>
            <li>
              <%= form_tag(search_path, :method => "get", class: "navbar-form", id: "search-form") do |f| %>
              <div class="form-group">
                <%= text_field_tag :keyword, params[:keyword], class: "form-control", placeholder: "Search events" %>
                <button type="submit" class="btn btn-default">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </div>
              <% end %>
            </li>
            <li class="dropdown dropdown-right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li id="user-email"><%= current_user.email %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
              </ul>
            </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/events.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/">Attending</a></li>
  <li role="presentation" class="active"><a href="/users/:id/events">Hosting</a></li>
</ul>
<div class="hosting">
  <h1>
    Events you're hosting:
  </h1>

  <% if current_user.events.count == 0 %>
  <h4>
    You're not hosting any events.
  </h4>
  <%= link_to 'Make one now!', new_event_path, class: "btn btn-primary btn-sm" %>
  <% else %>
  <div class="row">
      <% current_user.events.each do |event| %>

        <div class="col-sm-4 col-md-4 col-lg-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4><%= event.name %> <small>Hosted by <%= event.host %></small></h4>
            </div>
            <div class="panel-body">
              <p>
                <span class="glyphicon glyphicon-map-marker"></span>
                <%= event.location %>
              </p>
              <p>
                <span class="glyphicon glyphicon-time"></span>
                <%= event.timestart.strftime("%B %-d, %l:%M %p") %>
              </p>
              <p><%= link_to 'View', event, class: "btn btn-primary btn-sm" %> <%= link_to 'Edit', edit_event_path(event), class: "btn btn-default btn-sm" %></p>
            </div>
          </div>
        </div>
    
      <% end %>
  </div>
  <%= link_to 'New event', new_event_path, class: "btn btn-primary btn-sm" %>
  <% end %>
</div>

app/views/users/occasions.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="/">Attending</a></li>
  <li role="presentation"><a href="/users/:id/events">Hosting</a></li>
</ul>
<div class="attending">
  <h1>
    Events you're attending:
  </h1>

  <% if current_user.occasions.count == 0 %>
  <h4>
    You're not attending any events.
  </h4>
  <%= link_to 'Find one now!', events_path, class: "btn btn-primary btn-sm" %>
  <% else %>
  <div class="row">


      <% current_user.occasions.each do |event| %>
      <% cache do %>
        <div class="col-sm-4 col-md-4 col-lg-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4><%= event.name %> <small>Hosted by <%= event.host %></small></h4>
            </div>
            <div class="panel-body">
              <p>
                <span class="glyphicon glyphicon-map-marker"></span>
                <%= event.location %>
              </p>
              <p>
                <span class="glyphicon glyphicon-time"></span>
                <%= event.timestart.strftime("%B %-d, %l:%M %p") %>
              </p>
              <p><%= link_to 'View', event, class: "btn btn-primary btn-sm" %> <%= link_to 'Edit', edit_event_path(event), class: "btn btn-default btn-sm" %></p>
            </div>
          </div>
        </div>
       <% end %>

<% end %>

  </div>
  <%= link_to 'Find events', events_path, class: "btn btn-primary btn-sm" %>

 <% end %>
</div>